# Generated by Django 6.0.2 on 2026-02-17 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accession_number",
                    models.CharField(
                        help_text="Unique identifier for the plant accessions.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(help_text="Genus and species.", max_length=200),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        help_text="Common name if applicable.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(help_text="Date when the plant was acquired."),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the plant came from (nursery, donor, etc.).",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location in the garden or greenhouse.",
                        max_length=200,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("water", "Watering"),
                            ("fertilize", "Fertilizing"),
                            ("prune", "Pruning"),
                            ("repot", "Repotting"),
                            ("pest_control", "Pest Control"),
                            ("observation", "Observation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_events",
                        to="plants.plant",
                    ),
                ),
            ],
        ),
    ]
